# configuration file to set environment variables
# Gives developers control to set configurations during deployment only.
resource:
  name: cluster_logs
  path: clusterlogs
  defaultMessage: Logs Not Found